// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLR-4aNpjll8IYfpiDfHj015jDg2I-Rv8',
    appId: '1:277355287871:web:9d49ac3d5921deb1ccef8a',
    messagingSenderId: '277355287871',
    projectId: 'chatapp1stproject',
    authDomain: 'chatapp1stproject.firebaseapp.com',
    storageBucket: 'chatapp1stproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiNJlt1bF9WFHKKc8XNARe5BbR-iHvTqg',
    appId: '1:277355287871:android:366117ae5c4f8751ccef8a',
    messagingSenderId: '277355287871',
    projectId: 'chatapp1stproject',
    storageBucket: 'chatapp1stproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7dGCzYsYmKMxXgFipPCV2D22UodNDHOw',
    appId: '1:277355287871:ios:f7fce597333985d1ccef8a',
    messagingSenderId: '277355287871',
    projectId: 'chatapp1stproject',
    storageBucket: 'chatapp1stproject.appspot.com',
    iosClientId: '277355287871-ghbes0p4io8s40rm385a62svgsndf0du.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp1st',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7dGCzYsYmKMxXgFipPCV2D22UodNDHOw',
    appId: '1:277355287871:ios:043c76a4fbca0f9dccef8a',
    messagingSenderId: '277355287871',
    projectId: 'chatapp1stproject',
    storageBucket: 'chatapp1stproject.appspot.com',
    iosClientId: '277355287871-v0u8pjcdheotefo5ieglohiv765sp02m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp1st.RunnerTests',
  );
}
